name: Transfer ECS Services to Account B

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to transfer'
        required: false
        default: 'latest'
      task_family1:
        description: 'Task definition family name for service 1'
        required: false
        default: 'api-with-redis-task'
      task_family2:
        description: 'Task definition family name for service 2'
        required: false
        default: 'frontend-task'

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file for script
        run: |
          echo "Creating .env file for migration script"
          echo "ACCOUNT_A_REPO1=${{ secrets.ACCOUNT_A_REPO1 }}" >> .env
          echo "ACCOUNT_B_REPO1=${{ secrets.ACCOUNT_B_REPO1 }}" >> .env
          echo "ACCOUNT_A_REPO2=${{ secrets.ACCOUNT_A_REPO2 }}" >> .env
          echo "ACCOUNT_B_REPO2=${{ secrets.ACCOUNT_B_REPO2 }}" >> .env
          echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> .env
          echo "TASK_FAMILY1=${{ github.event.inputs.task_family1 }}" >> .env
          echo "TASK_FAMILY2=${{ github.event.inputs.task_family2 }}" >> .env
          echo "REGION=us-east-2" >> .env
          echo "OUT_FILE1=td1.json" >> .env
          echo "OUT_FILE2=td2.json" >> .env

      - name: Run migrate script (Account A)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_A }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_A }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          ./migrate.sh

      - name: Run migrate2 script (Account B)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_B }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_B }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          ./migrate2.sh

      - name: Create cluster and service Account B
        run: |
          terraform init
          terraform apply -auto-approve 
